import React from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import { Layout } from '../src/components';
import About from './about';
import Contact from './contact';
import Projects from './projects';
import Featured from './featured';
import Jobs from './jobs';
import Hero from './hero';
import { useRouter } from 'next/router';

const StyledMainContainer = styled.main`
  counter-reset: section;
`;

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout location={router}>
        <StyledMainContainer className="fillHeight">
          <Hero />
          <About />
          <Jobs />
          <Featured />
          <Projects />
          <Contact />
        </StyledMainContainer>
      </Layout>
    </>
  );
}
